version: 1.0


server:
  host: 0.0.0.0
  port: 8001

log:
  path: "app.log"
  level: -1 

database:
  mysql:
    host: localhost
    port: 3306
    user: root
    password: Jitu@2783
            db: myloanDB
            sslmode: disable

# certificate:
#   path: "./../pkg/middlewares/id_rsa.pub"
#   aes_private_key: "Ue[oPw5s_[k=u#W("
thirdparty: 
  restapi:
    retrycount : 2
    retrywaittime : 100
    timeout : 200
  grpc:
    kafka:
      url: "loanApp-grpc:8001"
      timeout: 500 